apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  - ./config.yaml
  - ./sops.yaml
images:
  - name: 716137715997.dkr.ecr.us-east-1.amazonaws.com/report-service-migration
    newTag: v0.51.0-fast-v1.0_f2abc642
  - name: 716137715997.dkr.ecr.us-east-1.amazonaws.com/report-service
    newTag: v0.51.0-fast-v1.0_f2abc642
